import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-foreign-trade-zone-duty-savings-compliance",
  "engine": "recovery",
  "title": "Foreign-Trade Zone Duty Savings & Compliance",
  "shortTitle": "FTZ Savings OS",
  "tagline": "Control merchandise status, inventory, production, entries, exports, and transaction-level duty savings",
  "industry": "Foreign-Trade Zone Operations",
  "uiPort": 4590,
  "apiPort": 5590,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Eligible FTZ duty savings realized with inventory integrity, CBP-ready evidence, and accurate annual reporting",
  "valueNarrative": "Connect zone admissions, HTS classifications, customs status, inventory, BOM consumption, transfers, exports, entries, scrap, duty, and annual reports.",
  "calculation": {
    "actualKey": "realizedSavings",
    "expectedKey": "eligibleSavings",
    "actualLabel": "Realized Duty Savings",
    "expectedLabel": "Calculated Eligible Savings",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "FTZ admission, inventory, production, disposition, and tariff evidence indicate unrealized duty savings or compliance exceptions.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("zone-and-activation-registry","FSO01","Zone and activation registry","Reconcile zone and activation registry using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed zone and activation registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Zone and activation registry Reference","text","FSO01-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("part-and-hts-classification","FSO02","Part and HTS classification","Reconcile part and hts classification using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed part and hts classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Part and HTS classification Reference","text","FSO02-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("foreign-and-domestic-status","FSO03","Foreign and domestic status","Reconcile foreign and domestic status using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed foreign and domestic status decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Foreign and domestic status Reference","text","FSO03-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("admission-transaction-ingestion","FSO04","Admission transaction ingestion","Reconcile admission transaction ingestion using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed admission transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Admission transaction ingestion Reference","text","FSO04-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("inventory-control-reconciliation","FSO05","Inventory control reconciliation","Reconcile inventory control reconciliation using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed inventory control reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Inventory control reconciliation Reference","text","FSO05-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("zone-to-zone-transfer-management","FSO06","Zone-to-zone transfer management","Reconcile zone-to-zone transfer management using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed zone-to-zone transfer management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Zone-to-zone transfer management Reference","text","FSO06-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("production-bom-consumption","FSO07","Production BOM consumption","Reconcile production bom consumption using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed production bom consumption decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Production BOM consumption Reference","text","FSO07-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("privileged-status-control","FSO08","Privileged status control","Reconcile privileged status control using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed privileged status control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Privileged status control Reference","text","FSO08-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("inverted-tariff-savings-calculation","FSO09","Inverted-tariff savings calculation","Reconcile inverted-tariff savings calculation using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed inverted-tariff savings calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Inverted-tariff savings calculation Reference","text","FSO09-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("duty-deferral-calculation","FSO10","Duty deferral calculation","Reconcile duty deferral calculation using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed duty deferral calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Duty deferral calculation Reference","text","FSO10-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("scrap-and-waste-treatment","FSO11","Scrap and waste treatment","Reconcile scrap and waste treatment using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed scrap and waste treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Scrap and waste treatment Reference","text","FSO11-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("export-and-destruction-relief","FSO12","Export and destruction relief","Reconcile export and destruction relief using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed export and destruction relief decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Export and destruction relief Reference","text","FSO12-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("entry-and-withdrawal-preparation","FSO13","Entry and withdrawal preparation","Reconcile entry and withdrawal preparation using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed entry and withdrawal preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Entry and withdrawal preparation Reference","text","FSO13-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("cbp-discrepancy-workflow","FSO14","CBP discrepancy workflow","Reconcile cbp discrepancy workflow using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed cbp discrepancy workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","CBP discrepancy workflow Reference","text","FSO14-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("ftz-annual-report-preparation","FSO15","FTZ annual report preparation","Reconcile ftz annual report preparation using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed ftz annual report preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","FTZ annual report preparation Reference","text","FSO15-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]}),
feature("duty-savings-and-compliance-analytics","FSO16","Duty savings and compliance analytics","Reconcile duty savings and compliance analytics using zone authorizations, admissions, part and HTS classifications, customs status, inventory control, zone transfers, production BOMs, withdrawals, exports, destruction, entries, duty rates, and annual reports.","Produce a governed duty savings and compliance analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["zoneTransaction","Zone / Transaction","text","FTZ-184 / ADMISSION-884120"],["caseReference","Duty savings and compliance analytics Reference","text","FSO16-2026-001"],["realizedSavings","Realized Duty Savings","currency",2175000],["eligibleSavings","Calculated Eligible Savings","currency",2860000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"realizedSavings",subjects:["Automotive production subzone","Pharmaceutical distribution zone","Electronics manufacturing zone","3PL general-purpose zone","Energy equipment subzone"]})
]);
